// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for BookingStatus.
const (
	BookingStatusActive    BookingStatus = "active"
	BookingStatusCancelled BookingStatus = "cancelled"
)

// Defines values for BookingStatusFilter.
const (
	BookingStatusFilterActive    BookingStatusFilter = "active"
	BookingStatusFilterAll       BookingStatusFilter = "all"
	BookingStatusFilterCancelled BookingStatusFilter = "cancelled"
)

// Defines values for ValidationErrorResponseCode.
const (
	ValidationErrorResponseCodeValidationError ValidationErrorResponseCode = "validation_error"
)

// AdminBookingsByDateResponse defines model for AdminBookingsByDateResponse.
type AdminBookingsByDateResponse struct {
	Date  openapi_types.Date `json:"date"`
	Items []BookingSummary   `json:"items"`
}

// AdminSessionLoginRequest defines model for AdminSessionLoginRequest.
type AdminSessionLoginRequest struct {
	Password string `json:"password"`
}

// BookingCreateRequest defines model for BookingCreateRequest.
type BookingCreateRequest struct {
	Comment *string `json:"comment"`

	// Date Дата записи (TZ студии)
	Date openapi_types.Date `json:"date"`

	// DurationMinutes Длительность (кратно slot_minutes). Сервер проверит, что весь интервал свободен.
	DurationMinutes int    `json:"duration_minutes"`
	Name            string `json:"name"`
	Phone           string `json:"phone"`

	// StartTime Время начала (кратно slot_minutes)
	StartTime string `json:"start_time"`
}

// BookingCreateResponse defines model for BookingCreateResponse.
type BookingCreateResponse struct {
	CreatedAt       time.Time          `json:"created_at"`
	Date            openapi_types.Date `json:"date"`
	DurationMinutes int                `json:"duration_minutes"`

	// EndTime Рассчитанное окончание (не включительно)
	EndTime   string             `json:"end_time"`
	Id        openapi_types.UUID `json:"id"`
	StartTime string             `json:"start_time"`
	Status    BookingStatus      `json:"status"`
}

// BookingDetail defines model for BookingDetail.
type BookingDetail struct {
	CancelReason    *string            `json:"cancel_reason"`
	CancelledAt     *time.Time         `json:"cancelled_at"`
	ClientName      string             `json:"client_name"`
	ClientPhone     string             `json:"client_phone"`
	Comment         *string            `json:"comment"`
	CreatedAt       time.Time          `json:"created_at"`
	Date            openapi_types.Date `json:"date"`
	DurationMinutes int                `json:"duration_minutes"`
	EndTime         string             `json:"end_time"`
	Id              openapi_types.UUID `json:"id"`
	StartTime       string             `json:"start_time"`
	Status          BookingStatus      `json:"status"`
}

// BookingStatus defines model for BookingStatus.
type BookingStatus string

// BookingStatusFilter defines model for BookingStatusFilter.
type BookingStatusFilter string

// BookingSummary defines model for BookingSummary.
type BookingSummary struct {
	CancelledAt     *time.Time         `json:"cancelled_at"`
	ClientName      string             `json:"client_name"`
	ClientPhone     string             `json:"client_phone"`
	Comment         *string            `json:"comment"`
	CreatedAt       time.Time          `json:"created_at"`
	Date            openapi_types.Date `json:"date"`
	DurationMinutes int                `json:"duration_minutes"`
	EndTime         string             `json:"end_time"`
	Id              openapi_types.UUID `json:"id"`
	StartTime       string             `json:"start_time"`
	Status          BookingStatus      `json:"status"`
}

// CancelBookingRequest defines model for CancelBookingRequest.
type CancelBookingRequest struct {
	Reason *string `json:"reason"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details"`
	Message string                  `json:"message"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// FreeSlotsResponse defines model for FreeSlotsResponse.
type FreeSlotsResponse struct {
	Date openapi_types.Date `json:"date"`

	// FreeSlots Свободные стартовые слоты по сетке (HH:MM)
	FreeSlots []string `json:"free_slots"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Code    ValidationErrorResponseCode `json:"code"`
	Fields  []FieldError                `json:"fields"`
	Message string                      `json:"message"`
}

// ValidationErrorResponseCode defines model for ValidationErrorResponse.Code.
type ValidationErrorResponseCode string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// AdminUnauthorized defines model for AdminUnauthorized.
type AdminUnauthorized = ErrorResponse

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// TimeConflict defines model for TimeConflict.
type TimeConflict = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ValidationErrorResponse

// AdminListBookingsByDateParams defines parameters for AdminListBookingsByDate.
type AdminListBookingsByDateParams struct {
	// Date Дата YYYY-MM-DD (часовой пояс студии)
	Date   openapi_types.Date   `form:"date" json:"date"`
	Status *BookingStatusFilter `form:"status,omitempty" json:"status,omitempty"`
}

// AdminCancelBookingParams defines parameters for AdminCancelBooking.
type AdminCancelBookingParams struct {
	// IdempotencyKey Ключ идемпотентности для безопасных повторов (ретраи/двойной клик).
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// CreateBookingParams defines parameters for CreateBooking.
type CreateBookingParams struct {
	// IdempotencyKey Ключ идемпотентности для безопасных повторов (ретраи/двойной клик).
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// GetFreeSlotsByDateParams defines parameters for GetFreeSlotsByDate.
type GetFreeSlotsByDateParams struct {
	// Date Дата YYYY-MM-DD (часовой пояс студии)
	Date openapi_types.Date `form:"date" json:"date"`
}

// AdminCancelBookingJSONRequestBody defines body for AdminCancelBooking for application/json ContentType.
type AdminCancelBookingJSONRequestBody = CancelBookingRequest

// AdminSessionLoginJSONRequestBody defines body for AdminSessionLogin for application/json ContentType.
type AdminSessionLoginJSONRequestBody = AdminSessionLoginRequest

// CreateBookingJSONRequestBody defines body for CreateBooking for application/json ContentType.
type CreateBookingJSONRequestBody = BookingCreateRequest
